services:
  # Auth # tokens and cache
  redis-auth:
    image: redis:7-alpine
    container_name: onechan-redis-auth
    ports:
      - "6379:6379"
    volumes:
      - redis_auth_data:/data
    restart: unless-stopped

  # Post # cache 
  redis-post:
    image: redis:7-alpine
    container_name: onechan-redis-post
    ports:
      - "6380:6379"
    volumes:
      - redis_post_cache_data:/data
    restart: unless-stopped
  
  # redis-stream-messenger:
  #   image: redis:7-alpine
  #   container_name: onechan-redis-messenger
  #   ports:
  #     - "6381:6379"
  #   restart: unless-stopped
  
  # notifications pub sub wala scene
  redis-notication: 
    image: redis:7-alpine
    container_name: onechan-redis-notification
    ports:
      - "6382:6379"
    restart: unless-stopped

  # authentication service 
  postgres-auth:
    image: postgres:16-alpine
    container_name: onechan-postgres-auth
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: AuthDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    restart: unless-stopped

  # postal service 
  postgres-post:
    image: postgres:16-alpine
    container_name: onechan-postgres-post
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
      POSTGRES_DB: PostDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_post_data:/var/lib/postgresql/data
    restart: unless-stopped

  # notif service 
  postgres-notification:
    image: postgres:16-alpine
    container_name: onechan-postgres-notification
    environment:
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: notification
      POSTGRES_DB: NotificationDB
    ports:
      - "5434:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  # Feed service
  postgres-feed:
    image: postgres:16-alpine
    container_name: onechan-postgres-feed
    environment:
      POSTGRES_USER: feed
      POSTGRES_PASSWORD: feed
      POSTGRES_DB: FeedDB
    ports:
      - "5435:5432"
    volumes:
      - postgres_feed_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  kong:
    image: kong:3.6
    container_name: onechan-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8010"
      # JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml:ro
    ports:
      - "8000:8000"   # fontend hits this 
      - "8010:8010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    
volumes:
  redis_auth_data:
  redis_post_cache_data:
  postgres_auth_data:
  postgres_post_data:
  postgres_notification_data:
  postgres_feed_data: